# Permitir conexões sem autenticação (bom para desenvolvimento local)
allow_anonymous true

# Porta padrão para o ESP32 (MQTT sobre TCP)
listener 1883
protocol mqtt

# Porta para o Frontend Web (MQTT sobre WebSockets)
listener 9001
protocol websockets
